name: cmp-vis
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - comm=0.1.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=1.2.0
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - ipykernel=6.23.1
  - ipython=8.14.0
  - jedi=0.18.2
  - jupyter_client=8.2.0
  - jupyter_core=5.3.1
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.1.1
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=3.5.3
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - pip:
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.7
    - coloredlogs==15.0.1
    - contourpy==1.1.0
    - cycler==0.11.0
    - deprecation==2.1.0
    - filelock==3.12.2
    - flatbuffers==23.5.26
    - fonttools==4.40.0
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.31.1
    - img2pdf==0.4.4
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - llvmlite==0.40.1
    - lxml==4.9.3
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.1
    - numba==0.57.1
    - numpy==1.24.4
    - onnxruntime==1.15.1
    - opencv-python-headless==4.8.0.74
    - pdf2image==1.16.3
    - pikepdf==7.2.0
    - pillow==9.5.0
    - pooch==1.7.0
    - protobuf==4.23.4
    - pymatting==1.1.8
    - pyparsing==3.0.9
    - pytorch-minimize==0.0.2
    - pywavelets==1.4.1
    - rembg==2.0.49
    - requests==2.31.0
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sympy==1.12
    - threadpoolctl==3.1.0
    - tifffile==2023.7.4
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tqdm==4.65.0
    - urllib3==2.0.3
    - xpyutils==0.0.4
